// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa11zLQhLQkYEQu0hO0A1ZjiOv_p5m-NQ',
    appId: '1:914023365184:web:50a4d86c0a9089fc29bda5',
    messagingSenderId: '914023365184',
    projectId: 'sdtq-telagailmu-yogyakarta',
    authDomain: 'sdtq-telagailmu-yogyakarta.firebaseapp.com',
    storageBucket: 'sdtq-telagailmu-yogyakarta.firebasestorage.app',
    measurementId: 'G-0GQX3BXKN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwu8AZo59mDCHI6QCKRFacAlM82DnCf2k',
    appId: '1:914023365184:android:0a7258da6d169e3729bda5',
    messagingSenderId: '914023365184',
    projectId: 'sdtq-telagailmu-yogyakarta',
    storageBucket: 'sdtq-telagailmu-yogyakarta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2I6JC-tuurhjesEOGplWx2g1V52kyQo4',
    appId: '1:914023365184:ios:afef989078f8b89f29bda5',
    messagingSenderId: '914023365184',
    projectId: 'sdtq-telagailmu-yogyakarta',
    storageBucket: 'sdtq-telagailmu-yogyakarta.firebasestorage.app',
    iosBundleId: 'com.sdtqtelagailmuyogyakarta.sdtqTelagailmuYogyakarta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2I6JC-tuurhjesEOGplWx2g1V52kyQo4',
    appId: '1:914023365184:ios:afef989078f8b89f29bda5',
    messagingSenderId: '914023365184',
    projectId: 'sdtq-telagailmu-yogyakarta',
    storageBucket: 'sdtq-telagailmu-yogyakarta.firebasestorage.app',
    iosBundleId: 'com.sdtqtelagailmuyogyakarta.sdtqTelagailmuYogyakarta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa11zLQhLQkYEQu0hO0A1ZjiOv_p5m-NQ',
    appId: '1:914023365184:web:903d3f4a298ed3a629bda5',
    messagingSenderId: '914023365184',
    projectId: 'sdtq-telagailmu-yogyakarta',
    authDomain: 'sdtq-telagailmu-yogyakarta.firebaseapp.com',
    storageBucket: 'sdtq-telagailmu-yogyakarta.firebasestorage.app',
    measurementId: 'G-7DNNHGEGQV',
  );
}
